### ISSUE TITLE
Crash in boost::asio::detail::epoll_reactor::start_op

### ISSUE THREAD

**Issue by mcepl** [SpectrumIM/spectrum2#133]
I have spectrum2 crashing on me quite frequently (like daily) in the RH-internal IRC-only server-mode instance:

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007fe669775de4 in boost::asio::detail::epoll_reactor::start_op (
    this=0x8dac10, op_type=op_type@entry=0, descriptor=8, 
    descriptor_data=@0x908698: 0x0, op=op@entry=0x7fe650001a80, 
    allow_speculative=allow_speculative@entry=true)
    at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:219
219 /usr/include/boost/asio/detail/impl/epoll_reactor.ipp: No such file or directory.
Missing separate debuginfos, use: debuginfo-install apr-1.4.8-3.el7.x86_64 apr-util-1.5.2-6.el7.x86_64 avahi-libs-0.6.31-15.el7_2.1.x86_64 boost-chrono-1.53.0-25.el7.x86_64 boost-date-time-1.53.0-25.el7.x86_64 boost-filesystem-1.53.0-25.el7.x86_64 boost-locale-1.53.0-25.el7.x86_64 boost-program-options-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-serialization-1.53.0-25.el7.x86_64 boost-signals-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 dbus-libs-1.6.12-13.el7.x86_64 expat-2.1.0-8.el7.x86_64 glibc-2.17-106.el7_2.4.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libcurl-7.29.0-25.el7.x86_64 libdb-5.3.21-19.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libstdc++-4.8.5-4.el7.x86_64 libuuid-2.23.2-26.el7_2.2.x86_64 log4cxx-0.10.0-16.el7.x86_64 mariadb-libs-5.5.47-1.el7_2.x86_64 nspr-4.11.0-1.el7_2.x86_64 nss-3.21.0-9.el7_2.x86_64 nss-softokn-freebl-3.16.2.3-14.2.el7_2.x86_64 nss-util-3.21.0-2.2.el7_2.x86_64 openldap-2.4.40-9.el7_2.x86_64 openssl-libs-1.0.1e-51.el7_2.4.x86_64 pcre-8.32-15.el7.x86_64 popt-1.13-16.el7.x86_64 postgresql-libs-9.2.15-1.el7_2.x86_64 protobuf-2.5.0-8.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) thread apply all backtrace
(gdb) thread apply all backtrace

Thread 4 (Thread 0x7fe66a1e08c0 (LWP 19998)):
#0  0x00007fe66683c6d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007fe66967f5b3 in wait (m=..., this=0x7ffded236f98)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::SimpleEventLoop::doRun (this=this@entry=0x7ffded236ef0, 
    breakAfterEvents=breakAfterEvents@entry=false)
    at Swiften/EventLoop/SimpleEventLoop.cpp:26
#3  0x0000000000460b64 in run (this=0x7ffded236ef0)
    at /usr/include/Swiften/EventLoop/SimpleEventLoop.h:22
#4  mainloop () at /usr/src/debug/spectrum2/spectrum/src/main.cpp:282
#5  0x000000000045b367 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/spectrum2/spectrum/src/main.cpp:512

Thread 3 (Thread 0x7fe656ef8700 (LWP 20001)):
#0  0x00007fe66683c6d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007fe6697b4c73 in wait (m=..., this=0x8e44c8)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::PlatformDomainNameResolver::run (this=0x8e4400)
    at Swiften/Network/PlatformDomainNameResolver.cpp:60
#3  0x00007fe668b6724a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#4  0x00007fe666838dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fe66433028d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fe64eef8700 (LWP 20000)):
#0  0x00007fe66683c6d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007fe6697bf663 in wait (m=..., this=0x8e9820)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::PlatformNATTraversalWorker::start (this=0x8e9760)
    at Swiften/Network/PlatformNATTraversalWorker.cpp:193
#3  0x00007fe668b6724a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#4  0x00007fe666838dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fe66433028d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fe6576f9700 (LWP 19999)):
#0  0x00007fe669775de4 in boost::asio::detail::epoll_reactor::start_op (
    this=0x8dac10, op_type=op_type@entry=0, descriptor=8, 
    descriptor_data=@0x908698: 0x0, op=op@entry=0x7fe650001a80, 
---Type <return> to continue, or q <return> to quit---
    allow_speculative=allow_speculative@entry=true)
    at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:219
#1  0x00007fe66977221b in start_op (noop=false, is_non_blocking=true, 
    op=0x7fe650001a80, op_type=0, impl=..., this=0x908c78)
    at /usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:212
#2  async_receive<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (
    handler=<error reading variable: access outside bounds of object referenced via synthetic pointer>, flags=0, buffers=..., impl=..., this=0x908c78)
    at /usr/include/boost/asio/detail/reactive_socket_service_base.hpp:277
#3  async_receive<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (handler=..., flags=0, 
    buffers=..., impl=..., this=0x908c50)
    at /usr/include/boost/asio/stream_socket_service.hpp:318
#4  async_read_some<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (handler=..., 
    buffers=..., this=0x908688)
    at /usr/include/boost/asio/basic_stream_socket.hpp:787
#5  Swift::BoostConnection::doRead (this=this@entry=0x9085b0)
    at Swiften/Network/BoostConnection.cpp:125
#6  0x00007fe66977432f in Swift::BoostConnection::handleSocketRead (
    this=0x9085b0, error=..., bytesTransferred=<optimized out>)
    at Swiften/Network/BoostConnection.cpp:133
#7  0x00007fe669776a73 in call<boost::shared_ptr<Swift::BoostConnection>, boost::system::error_code const, unsigned long> (b2=<synthetic pointer>, b1=..., u=..., 
    this=0x7fe6576f8b80) at /usr/include/boost/bind/mem_fn_template.hpp:271
#8  operator()<boost::shared_ptr<Swift::BoostConnection> > (a2=<optimized out>, 
    a1=..., u=..., this=0x7fe6576f8b80)
    at /usr/include/boost/bind/mem_fn_template.hpp:286
#9  operator()<boost::_mfi::mf2<void, Swift::BoostConnection, const boost::system::error_code&, long unsigned int>, boost::_bi::list2<const boost::system::error_code&, long unsigned int const&> > (a=<synthetic pointer>, f=..., 
    this=0x7fe6576f8b90) at /usr/include/boost/bind/bind.hpp:392
#10 operator()<boost::system::error_code, long unsigned int> (
    a2=@0x7fe6576f8bb0: 31, a1=..., this=0x7fe6576f8b80)
    at /usr/include/boost/bind/bind_template.hpp:102
#11 operator() (this=0x7fe6576f8b80)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/boost/asio/detail/bind_handler.hpp:118
#12 asio_handler_invoke<boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long> > (
    function=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#13 invoke<boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:39
#14 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > >::do_complete (owner=0x8e1a80, base=<optimized out>)
    at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:110
#15 0x00007fe669780046 in complete (bytes_transferred=17, ec=..., owner=..., 
    this=0x7fe650000980)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#16 do_run_one (ec=..., this_thread=..., lock=..., this=0x8e1a80)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:412
#17 run (ec=..., this=0x8e1a80)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#18 run (this=<optimized out>) at /usr/include/boost/asio/impl/io_service.ipp:59
#19 Swift::BoostIOServiceThread::doRun (this=<optimized out>)
    at Swiften/Network/BoostIOServiceThread.cpp:34
#20 0x00007fe668b6724a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#21 0x00007fe666838dc5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007fe66433028d in clone () from /lib64/libc.so.6
(gdb)
```

**Comment by mcepl** [comment]
And here is another one, but perhaps it is same?:
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f49456f0de4 in boost::asio::detail::epoll_reactor::start_op (
    this=0x8c2c10, op_type=op_type@entry=0, descriptor=10, 
    descriptor_data=@0x7f492c002d88: 0x0, op=op@entry=0x7f492c0043a0, 
    allow_speculative=allow_speculative@entry=true)
    at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:219
219	/usr/include/boost/asio/detail/impl/epoll_reactor.ipp: No such file or directory.
Missing separate debuginfos, use: debuginfo-install apr-1.4.8-3.el7.x86_64 apr-util-1.5.2-6.el7.x86_64 avahi-libs-0.6.31-15.el7_2.1.x86_64 boost-chrono-1.53.0-25.el7.x86_64 boost-date-time-1.53.0-25.el7.x86_64 boost-filesystem-1.53.0-25.el7.x86_64 boost-locale-1.53.0-25.el7.x86_64 boost-program-options-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-serialization-1.53.0-25.el7.x86_64 boost-signals-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 dbus-libs-1.6.12-13.el7.x86_64 expat-2.1.0-8.el7.x86_64 glibc-2.17-106.el7_2.4.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libcurl-7.29.0-25.el7.x86_64 libdb-5.3.21-19.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libstdc++-4.8.5-4.el7.x86_64 libuuid-2.23.2-26.el7_2.2.x86_64 log4cxx-0.10.0-16.el7.x86_64 mariadb-libs-5.5.47-1.el7_2.x86_64 nspr-4.11.0-1.el7_2.x86_64 nss-3.21.0-9.el7_2.x86_64 nss-softokn-freebl-3.16.2.3-14.2.el7_2.x86_64 nss-util-3.21.0-2.2.el7_2.x86_64 openldap-2.4.40-9.el7_2.x86_64 openssl-libs-1.0.1e-51.el7_2.4.x86_64 pcre-8.32-15.el7.x86_64 popt-1.13-16.el7.x86_64 postgresql-libs-9.2.15-1.el7_2.x86_64 protobuf-2.5.0-8.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) t a a bt
(gdb) t a a bt

Thread 4 (Thread 0x7f494615b8c0 (LWP 5468)):
#0  0x00007f49427b76d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007f49455fa5b3 in wait (m=..., this=0x7ffe4bd40978)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::SimpleEventLoop::doRun (this=this@entry=0x7ffe4bd408d0, 
    breakAfterEvents=breakAfterEvents@entry=false)
    at Swiften/EventLoop/SimpleEventLoop.cpp:26
#3  0x0000000000460b64 in run (this=0x7ffe4bd408d0)
    at /usr/include/Swiften/EventLoop/SimpleEventLoop.h:22
#4  mainloop () at /usr/src/debug/spectrum2/spectrum/src/main.cpp:282
#5  0x000000000045b367 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/spectrum2/spectrum/src/main.cpp:512

Thread 3 (Thread 0x7f4932673700 (LWP 5471)):
#0  0x00007f49427b76d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007f494572fc73 in wait (m=..., this=0x8cc4c8)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::PlatformDomainNameResolver::run (this=0x8cc400)
    at Swiften/Network/PlatformDomainNameResolver.cpp:60
#3  0x00007f4944ae224a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#4  0x00007f49427b3dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f49402ab28d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f4932e74700 (LWP 5470)):
#0  0x00007f49427b76d5 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x00007f494573a663 in wait (m=..., this=0x8d1820)
    at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  Swift::PlatformNATTraversalWorker::start (this=0x8d1760)
    at Swiften/Network/PlatformNATTraversalWorker.cpp:193
#3  0x00007f4944ae224a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#4  0x00007f49427b3dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f49402ab28d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f4933675700 (LWP 5469)):
#0  0x00007f49456f0de4 in boost::asio::detail::epoll_reactor::start_op (
    this=0x8c2c10, op_type=op_type@entry=0, descriptor=10, 
    descriptor_data=@0x7f492c002d88: 0x0, op=op@entry=0x7f492c0043a0, 
---Type <return> to continue, or q <return> to quit---
    allow_speculative=allow_speculative@entry=true)
    at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:219
#1  0x00007f49456ed21b in start_op (noop=false, is_non_blocking=true, 
    op=0x7f492c0043a0, op_type=0, impl=..., this=0x8f0c78)
    at /usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:212
#2  async_receive<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (
    handler=<error reading variable: access outside bounds of object referenced via synthetic pointer>, flags=0, buffers=..., impl=..., this=0x8f0c78)
    at /usr/include/boost/asio/detail/reactive_socket_service_base.hpp:277
#3  async_receive<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (handler=..., flags=0, 
    buffers=..., impl=..., this=0x8f0c50)
    at /usr/include/boost/asio/stream_socket_service.hpp:318
#4  async_read_some<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (handler=..., 
    buffers=..., this=0x7f492c002d78)
    at /usr/include/boost/asio/basic_stream_socket.hpp:787
#5  Swift::BoostConnection::doRead (this=this@entry=0x7f492c002ca0)
    at Swiften/Network/BoostConnection.cpp:125
#6  0x00007f49456ef32f in Swift::BoostConnection::handleSocketRead (
    this=0x7f492c002ca0, error=..., bytesTransferred=<optimized out>)
    at Swiften/Network/BoostConnection.cpp:133
#7  0x00007f49456f1a73 in call<boost::shared_ptr<Swift::BoostConnection>, boost::system::error_code const, unsigned long> (b2=<synthetic pointer>, b1=..., u=..., 
    this=0x7f4933674b80) at /usr/include/boost/bind/mem_fn_template.hpp:271
#8  operator()<boost::shared_ptr<Swift::BoostConnection> > (a2=<optimized out>, 
    a1=..., u=..., this=0x7f4933674b80)
    at /usr/include/boost/bind/mem_fn_template.hpp:286
#9  operator()<boost::_mfi::mf2<void, Swift::BoostConnection, const boost::system::error_code&, long unsigned int>, boost::_bi::list2<const boost::system::error_code&, long unsigned int const&> > (a=<synthetic pointer>, f=..., 
    this=0x7f4933674b90) at /usr/include/boost/bind/bind.hpp:392
#10 operator()<boost::system::error_code, long unsigned int> (
    a2=@0x7f4933674bb0: 31, a1=..., this=0x7f4933674b80)
    at /usr/include/boost/bind/bind_template.hpp:102
#11 operator() (this=0x7f4933674b80)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/boost/asio/detail/bind_handler.hpp:118
#12 asio_handler_invoke<boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long> > (
    function=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#13 invoke<boost::asio::detail::binder2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::system::error_code, unsigned long>, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > > (context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:39
#14 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, Swift::BoostConnection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<boost::shared_ptr<Swift::BoostConnection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > >::do_complete (owner=0x8c9a80, base=<optimized out>)
    at /usr/include/boost/asio/detail/reactive_socket_recv_op.hpp:110
#15 0x00007f49456fb046 in complete (bytes_transferred=17, ec=..., owner=..., 
    this=0x7f492c000a20)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#16 do_run_one (ec=..., this_thread=..., lock=..., this=0x8c9a80)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:412
#17 run (ec=..., this=0x8c9a80)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#18 run (this=<optimized out>) at /usr/include/boost/asio/impl/io_service.ipp:59
#19 Swift::BoostIOServiceThread::doRun (this=<optimized out>)
    at Swiften/Network/BoostIOServiceThread.cpp:34
#20 0x00007f4944ae224a in thread_proxy ()
   from /lib64/libboost_thread-mt.so.1.53.0
#21 0x00007f49427b3dc5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f49402ab28d in clone () from /lib64/libc.so.6
(gdb)
```

**Comment by mcepl** [comment]
Using (on RHEL-7):
```
boost-filesystem-1.53.0-25.el7.x86_64
boost-serialization-1.53.0-25.el7.x86_64
boost-timer-1.53.0-25.el7.x86_64
boost-iostreams-1.53.0-25.el7.x86_64
libcommuni-3.4.0-2.el7.centos.x86_64
boost-thread-1.53.0-25.el7.x86_64
boost-chrono-1.53.0-25.el7.x86_64
boost-locale-1.53.0-25.el7.x86_64
boost-atomic-1.53.0-25.el7.x86_64
swiften-3.0-0.6.rc2.el7.centos.x86_64
swift-debuginfo-3.0-0.6.rc2.el7.centos.x86_64
spectrum2-2.0.3-1.0.1.MC.gitfe69cbd.el7.centos.x86_64
boost-system-1.53.0-25.el7.x86_64
boost-date-time-1.53.0-25.el7.x86_64
boost-signals-1.53.0-25.el7.x86_64
boost-wave-1.53.0-25.el7.x86_64
boost-python-1.53.0-25.el7.x86_64
boost-math-1.53.0-25.el7.x86_64
boost-1.53.0-25.el7.x86_64
spectrum2-libcommuni-backend-2.0.3-1.0.1.MC.gitfe69cbd.el7.centos.x86_64
spectrum2-debuginfo-2.0.3-1.0.1.MC.gitfe69cbd.el7.centos.x86_64
boost-regex-1.53.0-25.el7.x86_64
boost-program-options-1.53.0-25.el7.x86_64
boost-graph-1.53.0-25.el7.x86_64
boost-context-1.53.0-25.el7.x86_64
boost-random-1.53.0-25.el7.x86_64
boost-test-1.53.0-25.el7.x86_64
```

**Comment by tfar** [comment]
Swift master (read future Swift 4.0) uses C++11, is Spectrum2 also built as C++11?

**Comment by mcepl** [comment]
> Swift master (read future Swift 4.0) uses C++11, is Spectrum2 also built as C++11?

??? What it has to do with anything? This is Swift 3.*

**Comment by HIPERCUBE** [comment]
Is there any solutions??

**Comment by vitalyster** [comment]
I'm still unable to reproduce, please update swiften to 4 and let me know if that crash appears again
