### ISSUE TITLE
2.0.10 crashes on start: Assertion failed: (this->is_initialized())

### ISSUE THREAD

**Issue by drook** [SpectrumIM/spectrum2#350]
Env:
````env
[root@elf:etc/spectrum2]# uname -a
FreeBSD elf.hq.norma.perm.ru 11.2-RELEASE-p3 FreeBSD 11.2-RELEASE-p3 #0 r338852: Tue Sep 25 21:25:31 YEKT 2018     emz@elf.hq.norma.perm.ru:/usr/obj/usr/src/sys/ELF  amd64

[root@elf:etc/spectrum2]# clang -v
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin

[root@elf:etc/spectrum2]# pkg info -x boost
boost-jam-1.69.0
boost-libs-1.69.0
````

Hello, I've just built 2.0.10 (not 2.0.10.1) and it crashes on start:

````launch
Assertion failed: (this->is_initialized()), function get, file /usr/local/include/boost/optional/optional.hpp, line 1207.
Abort trap (core dumped)
````

Backtrace:
````bt
[root@elf:etc/spectrum2]# gdb /usr/local/spectrum/bin/spectrum2_manager spectrum2_manager.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...

warning: core file may not match specified executable file.
Core was generated by `/usr/local/spectrum/bin/spectrum2_manager --config /usr/local/spectrum/etc/spect'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/local/spectrum/lib/libtransport.so.2.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/spectrum/lib/libtransport.so.2.0
Reading symbols from /usr/local/swiften/lib/libSwiften.so.4...done.
Loaded symbols for /usr/local/swiften/lib/libSwiften.so.4
Reading symbols from /usr/local/lib/libboost_system.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_system.so.1.69.0
Reading symbols from /usr/local/lib/libboost_thread.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_thread.so.1.69.0
Reading symbols from /usr/local/lib/libboost_regex.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_regex.so.1.69.0
Reading symbols from /usr/local/lib/libboost_program_options.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_program_options.so.1.69.0
Reading symbols from /usr/local/lib/libboost_filesystem.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_filesystem.so.1.69.0
Reading symbols from /usr/local/lib/libboost_serialization.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_serialization.so.1.69.0
Reading symbols from /usr/local/lib/libboost_date_time.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_date_time.so.1.69.0
Reading symbols from /lib/libz.so.6...Reading symbols from /usr/lib/debug//lib/libz.so.6.debug...done.
done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/lib/libssl.so.8...Reading symbols from /usr/lib/debug//usr/lib/libssl.so.8.debug...done.
done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /lib/libcrypto.so.8...Reading symbols from /usr/lib/debug//lib/libcrypto.so.8.debug...done.
done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /lib/libthr.so.3...Reading symbols from /usr/lib/debug//lib/libthr.so.3.debug...done.
done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/lib/libdl.so.1...Reading symbols from /usr/lib/debug//usr/lib/libdl.so.1.debug...done.
done.
Loaded symbols for /usr/lib/libdl.so.1
Reading symbols from /lib/libm.so.5...Reading symbols from /usr/lib/debug//lib/libm.so.5.debug...done.
done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /lib/libc.so.7...Reading symbols from /usr/lib/debug//lib/libc.so.7.debug...done.
done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/lib/libc++.so.1...Reading symbols from /usr/lib/debug//usr/lib/libc++.so.1.debug...done.
done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...Reading symbols from /usr/lib/debug//lib/libcxxrt.so.1.debug...done.
done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /usr/local/lib/libprotobuf.so.9...done.
Loaded symbols for /usr/local/lib/libprotobuf.so.9
Reading symbols from /usr/local/spectrum/lib/libtransport-plugin.so.2.0...done.
Loaded symbols for /usr/local/spectrum/lib/libtransport-plugin.so.2.0
Reading symbols from /usr/local/lib/libboost_locale.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_locale.so.1.69.0
Reading symbols from /usr/local/lib/libcurl.so.4...done.
Loaded symbols for /usr/local/lib/libcurl.so.4
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/mysql/libmysqlclient.so.18...done.
Loaded symbols for /usr/local/lib/mysql/libmysqlclient.so.18
Reading symbols from /usr/local/lib/liblog4cxx.so.10...done.
Loaded symbols for /usr/local/lib/liblog4cxx.so.10
Reading symbols from /usr/local/lib/libpopt.so.0...done.
Loaded symbols for /usr/local/lib/libpopt.so.0
Reading symbols from /usr/local/lib/libjsoncpp.so.1...done.
Loaded symbols for /usr/local/lib/libjsoncpp.so.1
Reading symbols from /lib/libgcc_s.so.1...Reading symbols from /usr/lib/debug//lib/libgcc_s.so.1.debug...done.
done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/local/lib/libicudata.so.55...done.
Loaded symbols for /usr/local/lib/libicudata.so.55
Reading symbols from /usr/local/lib/libicui18n.so.55...done.
Loaded symbols for /usr/local/lib/libicui18n.so.55
Reading symbols from /usr/local/lib/libicuuc.so.55...done.
Loaded symbols for /usr/local/lib/libicuuc.so.55
Reading symbols from /usr/local/lib/libboost_chrono.so.1.69.0...done.
Loaded symbols for /usr/local/lib/libboost_chrono.so.1.69.0
Reading symbols from /usr/local/lib/libidn.so.11...done.
Loaded symbols for /usr/local/lib/libidn.so.11
Reading symbols from /usr/lib/libssl.so.7...done.
Loaded symbols for /usr/lib/libssl.so.7
Reading symbols from /usr/lib/libheimntlm.so.11...Reading symbols from /usr/lib/debug//usr/lib/libheimntlm.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libheimntlm.so.11
Reading symbols from /usr/lib/libhx509.so.11...Reading symbols from /usr/lib/debug//usr/lib/libhx509.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libhx509.so.11
Reading symbols from /usr/lib/libcom_err.so.5...Reading symbols from /usr/lib/debug//usr/lib/libcom_err.so.5.debug...done.
done.
Loaded symbols for /usr/lib/libcom_err.so.5
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /usr/lib/libasn1.so.11...Reading symbols from /usr/lib/debug//usr/lib/libasn1.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libasn1.so.11
Reading symbols from /usr/lib/libwind.so.11...Reading symbols from /usr/lib/debug//usr/lib/libwind.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libwind.so.11
Reading symbols from /usr/lib/libheimbase.so.11...Reading symbols from /usr/lib/debug//usr/lib/libheimbase.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libheimbase.so.11
Reading symbols from /usr/lib/libroken.so.11...Reading symbols from /usr/lib/debug//usr/lib/libroken.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libroken.so.11
Reading symbols from /lib/libcrypt.so.5...Reading symbols from /usr/lib/debug//lib/libcrypt.so.5.debug...done.
done.
Loaded symbols for /lib/libcrypt.so.5
Reading symbols from /usr/lib/libkrb5.so.11...Reading symbols from /usr/lib/debug//usr/lib/libkrb5.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libkrb5.so.11
Reading symbols from /usr/lib/libgssapi.so.10...Reading symbols from /usr/lib/debug//usr/lib/libgssapi.so.10.debug...done.
done.
Loaded symbols for /usr/lib/libgssapi.so.10
Reading symbols from /usr/lib/libgssapi_krb5.so.10...Reading symbols from /usr/lib/debug//usr/lib/libgssapi_krb5.so.10.debug...done.
done.
Loaded symbols for /usr/lib/libgssapi_krb5.so.10
Reading symbols from /usr/local/lib/libaprutil-1.so.0...done.
Loaded symbols for /usr/local/lib/libaprutil-1.so.0
Reading symbols from /usr/local/lib/libdb-5.3.so.0...done.
Loaded symbols for /usr/local/lib/libdb-5.3.so.0
Reading symbols from /usr/local/lib/libgdbm.so.4...done.
Loaded symbols for /usr/local/lib/libgdbm.so.4
Reading symbols from /usr/local/lib/libexpat.so.1...done.
Loaded symbols for /usr/local/lib/libexpat.so.1
Reading symbols from /usr/local/lib/libapr-1.so.0...done.
Loaded symbols for /usr/local/lib/libapr-1.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/lib/librt.so.1...Reading symbols from /usr/lib/debug//usr/lib/librt.so.1.debug...done.
done.
Loaded symbols for /usr/lib/librt.so.1
Reading symbols from /usr/lib/libprivateheimipcc.so.11...Reading symbols from /usr/lib/debug//usr/lib/libprivateheimipcc.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libprivateheimipcc.so.11
Reading symbols from /libexec/ld-elf.so.1...Reading symbols from /usr/lib/debug//libexec/ld-elf.so.1.debug...done.
done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x000000080598f47a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x000000080598f47a in thr_kill () from /lib/libc.so.7
#1  0x000000080598f444 in __raise (s=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x000000080598f3b9 in abort () at /usr/src/lib/libc/stdlib/abort.c:65
#3  0x0000000803f54fe8 in boost::program_options::detail::common_config_file_iterator::allowed_option ()
   from /usr/local/lib/libboost_program_options.so.1.69.0
#4  0x0000000803f54a4a in boost::program_options::detail::common_config_file_iterator::get ()
   from /usr/local/lib/libboost_program_options.so.1.69.0
#5  0x0000000803f5fb24 in boost::program_options::parse_config_file<char> ()
   from /usr/local/lib/libboost_program_options.so.1.69.0
#6  0x0000000800e27801 in Transport::Config::load () from /usr/local/spectrum/lib/libtransport.so.2.0
#7  0x0000000800e22de1 in Transport::Config::load () from /usr/local/spectrum/lib/libtransport.so.2.0
#8  0x0000000800e2e3ba in Transport::Config::load () from /usr/local/spectrum/lib/libtransport.so.2.0
#9  0x00000000004dd641 in start_instances ()
#10 0x00000000004a3c1a in main ()
(gdb)
````

Could you please help me with that ?
Thanks.

**Comment by drook** [comment]
Oh, looks like this is simply caused by wrong syntax in transport config. When I write "something" forgetting to state "protocol=" spectrum2 starts to crash on launch.

**Comment by drook** [comment]
Way to go !
